[package]
name = "file-id-string"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60", features = ["Win32","Win32_Storage","Win32_Storage_FileSystem"] }