name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - name: Database
        run:  |
          set -ex
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -d -e runner
          createdb runner
          echo 'SELECT version();' | psql
          createdb drd
          psql drd < schema/schema.sql
          createdb test
          psql test < schema/schema.sql
      - name: Update Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Tidy
        run: cargo fmt --check